### ISSUE TITLE
Composer + Failed to download caffeinated/presenter

### ISSUE THREAD

**Issue by kaidesu** [caffeinated/presenters#1]
```
- Installing caffeinated/presenter (v1.0.1)
    Downloading: Connecting...    Failed to download caffeinated/presenter from dist: The "https://api.github.com/repos/caffeinated/presenter/zipball/5001cfc47665f57c0c6ecd9d87072d52ea79584f" file could not be downloaded (HTTP/1.1 404 Not Found)
    Now trying to download from source
- Installing caffeinated/presenter (v1.0.1)
  Cloning 5001cfc47665f57c0c6ecd9d87072d52ea79584f
```

**Comment by illuminate3** [comment]
➜  rakkoII git:(master) ✗ composer require caffeinated/presenters=~2.0
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package caffeinated/presenters could not be found in any version, there may be a typo in the package name.

Potential causes:
- A typo in the package name
- The package is not available in a stable-enough version according to your minimum-stability setting
  see https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion for more details.

Read https://getcomposer.org/doc/articles/troubleshooting.md for further common problems.

Installation failed, reverting ./composer.json to its original content.
